/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anthonytepach.vistas.internos;

import com.anthonytepach.beans.Proyecto;
import com.anthonytepach.configuracion.LoggerRegistros;
import com.anthonytepach.configuracion.ValidacionEvents;
import com.anthonytepach.controlador.C_Cliente;
import com.anthonytepach.controlador.C_Proyecto;
import com.anthonytepach.vistas.VMenu;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Tepach
 */
public class NewProject extends javax.swing.JInternalFrame {

    LoggerRegistros loggger = new LoggerRegistros(this.getClass());
    /**
     * Creates new form NewProject
     */
    Date now = new Date();
    ArrayList<String> arrayRFC = new ArrayList<>();
    ValidacionEvents ve=new ValidacionEvents();
    public NewProject(String titulo) {
        initComponents();
        dateFormat();
        this.setTitle(titulo);
        if (titulo.contains("Registro")) {
            jtf_alta.setText(now.getYear() + 1900 + "-" + String.format("%02d", now.getMonth() + 1) + "-" + String.format("%02d", now.getDate()));
            cargarClientes();
            if (jcb_cliente.getItemCount() == 0) {
                boolean isNo = false;
                JOptionPane.showMessageDialog(rootPane, "No podras continuar sin dar de alta a clientes", "No hay ningún cliente registrado.", JOptionPane.INFORMATION_MESSAGE);
                jbtn_siguiente.setEnabled(isNo);
                jcb_cliente.setEnabled(isNo);
            }
        }
    }

    public NewProject(String titulo, String clave) {
        initComponents();
        dateFormat();
        this.setTitle(titulo);
        if (titulo.contains("Actualiza")) {
            jtf_alta.disable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void dateFormat() {
        jdch_ffin.setDateFormatString("yyyy-MM-dd");
        jdch_fini.setDateFormatString("yyyy-MM-dd");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estregasParciales = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcb_cliente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jcb_tipoproyecto = new javax.swing.JComboBox<>();
        jrb_si = new javax.swing.JRadioButton();
        jrb_nno = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_Proyecto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_lider = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Desc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_alta = new javax.swing.JTextField();
        jdch_ffin = new com.toedter.calendar.JDateChooser();
        jdch_fini = new com.toedter.calendar.JDateChooser();
        jtf_costototal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_cantidad = new javax.swing.JTextField();
        jbtn_siguiente = new javax.swing.JButton();

        setClosable(true);
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Cliente");

        jcb_cliente.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Tipo de proyecto");

        jcb_tipoproyecto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_tipoproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propios", "Acuerdo", "Contrato" }));

        estregasParciales.add(jrb_si);
        jrb_si.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jrb_si.setText("Si");

        estregasParciales.add(jrb_nno);
        jrb_nno.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jrb_nno.setSelected(true);
        jrb_nno.setText("No");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Entregas Parciales");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Nombre del proyecto");

        jtf_Proyecto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Lider de Proyecto");

        jtf_lider.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jta_Desc.setColumns(20);
        jta_Desc.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jta_Desc.setRows(5);
        jScrollPane1.setViewportView(jta_Desc);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Descripción breve del proyecto");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Fecha Inicio:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Fecha Fin:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de alta");

        jtf_alta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtf_alta.setEnabled(false);

        jdch_ffin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jdch_fini.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_costototal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_costototalKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Costo total:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Cantidad:");

        jtf_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cantidadKeyTyped(evt);
            }
        });

        jbtn_siguiente.setText("Siguente");
        jbtn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_tipoproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrb_si)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrb_nno)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jcb_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_Proyecto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdch_fini, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jdch_ffin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_alta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jbtn_siguiente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_costototal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtf_lider)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tipoproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_si)
                    .addComponent(jrb_nno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_lider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_costototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_alta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdch_fini, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdch_ffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jbtn_siguiente))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_siguienteActionPerformed
        int resouesta = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de guardar el proyecto?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resouesta == 0) {
            C_Proyecto cp = new C_Proyecto();
            Proyecto p = getData();
            cp.insertDB(p, rootPane);
            RegistrarOP rop = new RegistrarOP(p);
            VMenu.jdp_principal.add(rop);
            rop.toFront();
            rop.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jbtn_siguienteActionPerformed

    private void jtf_costototalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_costototalKeyTyped
        // TODO add your handling code here:
        ve.esDigito(evt);
    }//GEN-LAST:event_jtf_costototalKeyTyped

    private void jtf_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cantidadKeyTyped
        // TODO add your handling code here:
        ve.esDigito(evt);
    }//GEN-LAST:event_jtf_cantidadKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup estregasParciales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_siguiente;
    private javax.swing.JComboBox<String> jcb_cliente;
    private javax.swing.JComboBox<String> jcb_tipoproyecto;
    private com.toedter.calendar.JDateChooser jdch_ffin;
    private com.toedter.calendar.JDateChooser jdch_fini;
    private javax.swing.JRadioButton jrb_nno;
    private javax.swing.JRadioButton jrb_si;
    private javax.swing.JTextArea jta_Desc;
    private javax.swing.JTextField jtf_Proyecto;
    private javax.swing.JTextField jtf_alta;
    private javax.swing.JTextField jtf_cantidad;
    private javax.swing.JFormattedTextField jtf_costototal;
    private javax.swing.JTextField jtf_lider;
    // End of variables declaration//GEN-END:variables

    private void cargarClientes() {
        C_Cliente cli = new C_Cliente();
        ResultSet clientes = null;
        try {
            clientes = cli.getClients();
            while (clientes.next()) {
                jcb_cliente.addItem(clientes.getString(2));
                arrayRFC.add(clientes.getString(1));
            }
        } catch (Exception ex) {
            loggger.setError(ex.getMessage(), ex.fillInStackTrace());
        }
    }

    private Proyecto getData() {
        Proyecto pro = new Proyecto();
        C_Proyecto cpro = new C_Proyecto();
        pro.setTipo((String) jcb_tipoproyecto.getSelectedItem());
        pro.setCliente(arrayRFC.get(jcb_cliente.getSelectedIndex()));
        pro.setNombre(jtf_Proyecto.getText());
        pro.setLider(jtf_lider.getText());
        pro.setDescripcion(jta_Desc.getText());
        pro.setFecha_inicio(jdch_fini.getDate());
        pro.setFecha_fin(jdch_ffin.getDate());
        pro.setFecha_alta(jtf_alta.getText());
        pro.setClave(cpro.generarClave(pro.getTipo()));
        pro.setCosto(Integer.parseInt(jtf_costototal.getText()));
        pro.setVol_total(Integer.parseInt(jtf_cantidad.getText()));
        String ep = null;
        if (jrb_si.isSelected()) {
            ep = "Si";
        } else if (jrb_nno.isSelected()) {
            ep = "No";
        }
        pro.setEntrega_parcial(ep);
        return pro;
    }

}
