/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anthonytepach.vistas.internos;

import com.anthonytepach.beans.OrdenProduccion;
import com.anthonytepach.beans.Proyecto;
import com.anthonytepach.configuracion.LoggerRegistros;
import com.anthonytepach.configuracion.ValidacionEvents;
import com.anthonytepach.controlador.C_OrdenProduccion;
import com.anthonytepach.controlador.C_Producto;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Tepach
 */
public class RegistrarOP extends javax.swing.JInternalFrame {

    LoggerRegistros loggger = new LoggerRegistros(this.getClass());
    ValidacionEvents ve = new ValidacionEvents();
    ArrayList<String> arrayCod = new ArrayList<>();

    /**
     * Creates new form RegistrarOP
     */
    public RegistrarOP() {
        initComponents();
    }
    static String clave_proyecto;

    RegistrarOP(Proyecto data) {
        initComponents();
        carbarCombo();
        dateFormat();
        clave_proyecto = data.getClave();
        this.setTitle("Proyecto: " + data.getNombre() + "\t Clave: " + clave_proyecto);
        jtf_op.setText(getOPini());

    }
    RegistrarOP(String clave,String proyecto) {
        initComponents();
        carbarCombo();
        dateFormat();
        clave_proyecto = clave;
        this.setTitle("Proyecto: "+proyecto+"\t Clave: " + clave_proyecto);
        jtf_op.setText(getOPini());

    }

    private void dateFormat() {
        jdch_ffin.setDateFormatString("yyyy-MM-dd");
        jdch_fini.setDateFormatString("yyyy-MM-dd");
    }
    private String getOPini(){
        return  String.valueOf(new Date().getYear() + 1900).substring(2, 4) + String.format("%02d", new Date().getMonth() + 1) + "-";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_Tipodeop = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtf_op = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_cotizacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdch_fini = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jdch_ffin = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jcb_productos = new javax.swing.JComboBox<>();
        jbtn_guardar = new javax.swing.JButton();
        jrb_normal = new javax.swing.JRadioButton();
        jrb_rush = new javax.swing.JRadioButton();
        jrb_reproceso = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_nombreforma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_desc_froma = new javax.swing.JTextArea();
        jbtn_cancelar = new javax.swing.JButton();

        jLabel1.setText("N° Orden de Producción");

        jLabel2.setText("N° Cotización");

        jtf_cotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cotizacionKeyTyped(evt);
            }
        });

        jLabel3.setText("Fecha Inicio");

        jLabel4.setText("Fecha Fin");

        jLabel5.setText("Selecciona el producto:");

        jbtn_guardar.setText("Agregar");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        btnG_Tipodeop.add(jrb_normal);
        jrb_normal.setText("Normal");

        btnG_Tipodeop.add(jrb_rush);
        jrb_rush.setText("Rush");

        btnG_Tipodeop.add(jrb_reproceso);
        jrb_reproceso.setText("Reproceso");

        jLabel6.setText("Tipo");

        jLabel7.setText("Nombre de la forma");

        jLabel8.setText("Descripccion de la forma");

        jta_desc_froma.setColumns(20);
        jta_desc_froma.setRows(5);
        jScrollPane1.setViewportView(jta_desc_froma);

        jbtn_cancelar.setText("Cancelar");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jtf_nombreforma)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_op, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jdch_fini, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jdch_ffin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtf_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrb_normal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrb_rush)
                            .addGap(37, 37, 37)
                            .addComponent(jrb_reproceso))
                        .addComponent(jLabel6)
                        .addComponent(jcb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_guardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdch_fini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdch_ffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_normal)
                            .addComponent(jrb_rush)
                            .addComponent(jrb_reproceso))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nombreforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardar)
                    .addComponent(jbtn_cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_cotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cotizacionKeyTyped
        // TODO add your handling code here:
        ve.esDigito(evt);
    }//GEN-LAST:event_jtf_cotizacionKeyTyped

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        guardarOP();
        int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Desea agregar otra orden de producción?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta == 1) {
            this.dispose();
        }else{
            limpiar();
        }
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        // TODO add your handling code here:
         int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea cancelar?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void carbarCombo() {
        C_Producto cpro = new C_Producto();
        ResultSet consulta;
        try {
            consulta = cpro.getProducts();
            while (consulta.next()) {
                jcb_productos.addItem(consulta.getString(2));
                arrayCod.add(consulta.getString(1));
            }
        } catch (Exception ex) {
            loggger.setError(ex.getMessage(), ex.fillInStackTrace());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_Tipodeop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JComboBox<String> jcb_productos;
    private com.toedter.calendar.JDateChooser jdch_ffin;
    private com.toedter.calendar.JDateChooser jdch_fini;
    private javax.swing.JRadioButton jrb_normal;
    private javax.swing.JRadioButton jrb_reproceso;
    private javax.swing.JRadioButton jrb_rush;
    private javax.swing.JTextArea jta_desc_froma;
    private javax.swing.JTextField jtf_cotizacion;
    private javax.swing.JTextField jtf_nombreforma;
    private javax.swing.JTextField jtf_op;
    // End of variables declaration//GEN-END:variables

    private void guardarOP() {
        try {
            C_OrdenProduccion c_op = new C_OrdenProduccion();
            c_op.insertOP(getData(), rootPane);
        } catch (Exception ex) {
            loggger.setError(ex.getMessage(), ex.fillInStackTrace());
        }
    }

    private OrdenProduccion getData() {
        OrdenProduccion op = new OrdenProduccion();
        String type = null;
        op.setNo_op(jtf_op.getText());
        if (jrb_normal.isSelected()) {
            type = "Normal";
        } else if (jrb_rush.isSelected()) {
            type = "Rush";
        } else if (jrb_reproceso.isSelected()) {
            type = "Reproceso";
        }
        op.setTipo(type);
        op.setFecha_ini(jdch_fini.getDate());
        op.setFecha_fin(jdch_ffin.getDate());
        op.setStatus("Produccion");
        op.setProducto(arrayCod.get(jcb_productos.getSelectedIndex()));
        op.setClave_proyecto(clave_proyecto);
        op.setNo_cotizacion(jtf_cotizacion.getText());
        op.setDesc(jta_desc_froma.getText());
        op.setNom_forma(jtf_nombreforma.getText());
        return op;
    }

    private void limpiar() {
        jtf_op.setText(getOPini());
        if (jrb_normal.isSelected()) {
           jrb_normal.setSelected(false);
        } else if (jrb_rush.isSelected()) {
           jrb_rush.setSelected(false);
        } else if (jrb_reproceso.isSelected()) {
           jrb_reproceso.setSelected(false);
        }
        jdch_ffin.setDate(null);
        jdch_fini.setDate(null);
        jcb_productos.setSelectedIndex(-1);
        jtf_nombreforma.setText(null);
        jta_desc_froma.setText(null);
        jtf_cotizacion.setText(null);
    }
}
