/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anthonytepach.vistas.internos;

import com.anthonytepach.configuracion.LoggerRegistros;
import com.anthonytepach.controlador.C_OrdenProduccion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Tepach
 */
public class V_ConsultaOP extends javax.swing.JInternalFrame {

    LoggerRegistros loggger = new LoggerRegistros(this.getClass());
    /**
     * Creates new form V_ConsultaOP
     */
    String clave_proyecto;

    public V_ConsultaOP(String cp) {
        initComponents();
        clave_proyecto = cp;
        this.setTitle("Ordenes de produccion del proyecto " + clave_proyecto);
        cargarTabla();
        if (jtl_op.getRowCount()==0) {
            
             JOptionPane.showMessageDialog(rootPane,"No hay ninguna orden de producción asignda a este proyecto","Error",JOptionPane.WARNING_MESSAGE);
             dispose();
             setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_op = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        jtl_op.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtl_op.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_opMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtl_op);

        getContentPane().add(jScrollPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtl_opMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_opMouseClicked
        // TODO add your handling code here:
        int column = jtl_op.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jtl_op.getRowHeight();
        if (row < jtl_op.getRowCount() && row >= 0 && column < jtl_op.getColumnCount() && column >= 0) {
            Object value = jtl_op.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton bnt = (JButton) value;
                jtl_op.getValueAt(row, 3);
                JOptionPane.showMessageDialog(rootPane,jtl_op.getValueAt(row, 2),"Descripción",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtl_opMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtl_op;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        C_OrdenProduccion cop = new C_OrdenProduccion();
        try {
            cop.verTabla(jtl_op, clave_proyecto);
        } catch (Exception ex) {
            loggger.setError(ex.getMessage(), ex.fillInStackTrace());
        }
    }
}
