/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anthonytepach.vistas;

import com.anthonytepach.beans.Usuarios;
import com.anthonytepach.controlador.C_Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Tepach
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form VLogin
     */
    private Usuarios usuarioLogeado;

    public VLogin() {
        initComponents();
        VLogin.setDefaultLookAndFeelDecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jl_exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jps_password = new javax.swing.JPasswordField();
        linea_usuario = new javax.swing.JLabel();
        linea_password = new javax.swing.JLabel();
        img_candado = new javax.swing.JLabel();
        img_user = new javax.swing.JLabel();
        jbtn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 174, 239));

        jPanel1.setBackground(new java.awt.Color(28, 29, 77));

        jPanel3.setBackground(new java.awt.Color(195, 0, 62));

        jl_exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jl_exit.setForeground(new java.awt.Color(255, 255, 255));
        jl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_exit.setText("X");
        jl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/images/logo.png"))); // NOI18N

        jtf_usuario.setBackground(new java.awt.Color(28, 29, 77));
        jtf_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jtf_usuario.setBorder(null);
        jtf_usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jtf_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jps_password.setBackground(new java.awt.Color(28, 29, 77));
        jps_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jps_password.setForeground(new java.awt.Color(255, 255, 255));
        jps_password.setBorder(null);
        jps_password.setCaretColor(new java.awt.Color(255, 255, 255));
        jps_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jps_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jps_passwordActionPerformed(evt);
            }
        });

        linea_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/images/linea.png"))); // NOI18N

        linea_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/images/linea.png"))); // NOI18N

        img_candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/images/32x32/padlock(1).png"))); // NOI18N

        img_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tepach/images/32x32/user(1).png"))); // NOI18N

        jbtn_login.setBackground(new java.awt.Color(0, 174, 239));
        jbtn_login.setText("Iniciar");
        jbtn_login.setBorder(null);
        jbtn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_candado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jps_password, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linea_password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linea_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(img_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linea_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img_candado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jps_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea_password, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_exitMouseClicked
        System.gc();
        int a = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Thread.sleep(1000);
                JOptionPane.showMessageDialog(rootPane, "Hasta pronto", "Saliendo....", JOptionPane.INFORMATION_MESSAGE);
            } catch (InterruptedException ex) {
                Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(a);
        }

    }//GEN-LAST:event_jl_exitMouseClicked

    private void jbtn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_loginActionPerformed
        // TODO add your handling code here:
        if (validarVacios()) {
            login();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar todos los datos");
        }

    }//GEN-LAST:event_jbtn_loginActionPerformed

    private void jps_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jps_passwordActionPerformed
        // TODO add your handling code here:
        if (validarVacios()) {
            login();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar todos los datos");
        }
    }//GEN-LAST:event_jps_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
           
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_candado;
    private javax.swing.JLabel img_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JLabel jl_exit;
    private javax.swing.JPasswordField jps_password;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JLabel linea_password;
    private javax.swing.JLabel linea_usuario;
    // End of variables declaration//GEN-END:variables

    private void login() {
        Usuarios user = new Usuarios();
        user.setUsername(jtf_usuario.getText());
        user.setPassword(jps_password.getText());
        C_Usuario cu = new C_Usuario();
        if (cu.loguear(user)) {
            this.setVisible(false);
            VMenu vm = new VMenu(cu.getUserL());
            vm.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario y/o contraseña son incorrectos", "Datos invalidos", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Usuarios getUsuarioLogeado() {
        return usuarioLogeado;
    }

    public void setUsuarioLogeado(Usuarios usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }

    private boolean validarVacios() {
        return !(jtf_usuario.getText().isEmpty() && jps_password.getText().isEmpty());
    }

}
